name: CI
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
        env:
          CI: true

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - run: yarn affected:test

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - run: yarn affected:lint

